title: Create the database

steps:
  - title: Create the database
    class:
    code: |
      ```sql
      CREATE DATABASE example DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      ```

  - title: Create the user and configure the privileges
    class:
    code: |
      ```sql
      CREATE USER 'example'@'localhost' IDENTIFIED BY 'example';
      GRANT ALL PRIVILEGES ON example.* TO 'example'@'localhost';
      FLUSH PRIVILEGES;
      ```
